ProductListView (1차 중간 리뷰 요청)
wecode-bootcamp-korea/31-2nd-OldVintage-backend pull request #6
Opened 2022-04-15 08:05 UTC by angrybirdpark

## :: 최근 작업 주제 (하나 이상의 주제를 선택해주세요.)
- [x] 기능 추가
- [ ] 리뷰 반영
- [ ] 리팩토링
- [ ] 버그 수정
- [ ] 컨벤션 수정

<br />

## :: 구현 목표 (해당 브랜치에서 구현하고자 하는 하나의 목표를 설정합니다.)
- 상품 리스트 페이지 구현
- 해당 view의 test.py 작성

<br />

## :: 구현 사항 설명 (작업한 내용을 상세하게 기록합니다.)
1. view 작성
- 쿼리 파라미터를 이용한 다중 필터 구현
- GET 메소드를 이용해 Product의 정보 전송

2. test 작성
- 해당 테스트 내용을 setup 한 뒤, result의 length와 status_code 로 성공/실패 구현

<br />

## :: 성장 포인트 (해당 기능을 구현하며 고민했던 사항이나 새로 알게된 부분, 어려웠던 점 등을 작성합니다.)
- 쿼리파라미터를 좀 더 다양하게 이용할 수 있게 됐습니다.
- test.py를 이용해, 셋팅값과 예상 결과를 작성할 수 있게 됐습니다.

<br />

## :: 기타 질문 및 특이 사항

2022-04-15 08:07 UTC, angrybirdpark commented
멘토님! 우선 제대로 된 방향으로 가고 있는 지, 중간 완성본으로 리뷰 요청 드립니다!!
그 중에서도 제일 궁금한 부분은
1) 쿼리파라미터와 GET 부분을 클래스로 나누는 게 좋을 지,
2) 위처럼 해야한다면 test.py는 어떻게 진행되어야 할 지 가 궁금합니다..!

+ test.py가 제가 이해한대로 작성했는데 빠뜨린 점이 있을 지도 궁금합니다! (test.py의 경우 쿼리파라미터는 우선 배제하고 완성했습니다..!)

2022-04-15 08:57 UTC, lordmyshepherd requested changes

2022-04-15 08:57 UTC, lordmyshepherd commented on oldvintage/urls.py
> +    path('products', include('products.urls')),
👍🏻

2022-04-15 08:57 UTC, lordmyshepherd commented on products/tests.py
> +from users.models    import *
`import *`을 사용하지 말고 사용하는 모듈만 import해서 사용해주세요.
이유는 왜 그럴까요?

2022-04-15 08:57 UTC, lordmyshepherd commented on products/tests.py
> +        self.assertEqual(response.status_code, 200)
test코드는 결과값을 전체를 비교해줘야 정확하게 테스트를 할 수 있습니다.
만약에 view에서 반환하는 결과의 key 값이 달라진다면, 길이만 비교해서는 성공으로 넘어갈 수 있습니다.

최대한 리턴되는 결과를 전부 테스트 해주세요.
추가로 1, 0, -1 모든 케이스를 테스트하기 어렵다면 성공과 실패 케이스 반드시 테스트해주세요.

2022-04-15 08:57 UTC, lordmyshepherd commented on products/views.py
> +            q &= Q(pairings__id__in = pairing_id)
if문이 굉장히 많네요.

좋은 코드는 로직이 분기(조건문에 의해서 갈라짐)되지 않고, 선형적으로 작성된 코드입니다.
여기서 선형적이라는 의미는 파이썬이 코드를 위에서 아래로 실행할 때, if문을 만나서 분기되지 않고 하나의 흐름을 갖는 것을 말합니다. if문이 많으면 그만큼 코드에 경우의 수가 많아지기 때문에 나중에 디버깅하기가 어렵습니다.

if문을 줄일 수 있는 방법은 자료구조를 이용하는 방법이 있습니다. 아래 예제 코드를 한번 참고해보세요~~
```python
def get(self, request):
#        category_id   = request.GET.get('category_id', None)
#        offset        = int(request.GET.get('offset', 0))
#        limit         = int(request.GET.get('limit', 100))
#        ingredient_id = request.GET.getlist('ingredient_id', None)
#        skintype_id   = request.GET.getlist('skintype', None)
#        feeling_id    = request.GET.get('feeling_id', None)
#        badge         = request.GET.getlist('badge', None)

        FILTER_SET = {
            "category_id"   : "category__id",
            "badge"         : "badge__in",
            "ingredient_id" : "productingredient__ingredient__id__in",
            "skintype_id"   : "skintypes__skin_type__id__in",
            "feeling_id"    : "productfeelings__feeling__id__in"
        }

        query = { FILTER_SET[key] : value for key, value in request.GET.items()}
        
        products = Product.objects.filter(**query)

```

2022-04-15 08:58 UTC, lordmyshepherd requested changes

2022-04-15 08:58 UTC, lordmyshepherd commented on products/views.py
> +                'rating_count' : Review.objects.filter(product = product).count(),
이부분은 line 37 코드에 `annotate()` method를 사용해서 리펙토링해보세요~
```suggestion
                'rating_count' : Review.objects.filter(product = product).count(),
```

2022-04-15 08:58 UTC, lordmyshepherd commented on products/views.py
> +                'rating_score' : round(sum([review.rating for review in Review.objects.filter(product = product)]) / Review.objects.filter(product = product).count(),2)
이부분도 annotate 혹은 aggregate를 사용해서 더 좋은 코드로 바뀔 수 있을 것 같습니다.

2022-04-15 09:17 UTC, angrybirdpark commented on products/tests.py
> +from users.models    import *
어떤 걸 import했는지 알 방법이 없고 다른 앱끼리 같은 이름이 있다면 충돌 가능성도 있을 것 같습니다.
사용하는 모듈만 import해서 수정하겠습니다.

2022-04-17 11:04 UTC, angrybirdpark commented on products/views.py
> +            q &= Q(pairings__id__in = pairing_id)
getlist와 get을 불러들이는 방법이 달라서, 두가지 딕셔너리를 합치는 방향으로 진행했습니다..!

2022-04-17 11:05 UTC, angrybirdpark commented on products/views.py
> +                'rating_count' : Review.objects.filter(product = product).count(),
annotate를 활용하여 변경완료했습니다.

2022-04-17 11:05 UTC, angrybirdpark commented on products/views.py
> +                'rating_score' : round(sum([review.rating for review in Review.objects.filter(product = product)]) / Review.objects.filter(product = product).count(),2)
annotate를 활용하여 변경완료했습니다.

2022-04-17 11:15 UTC, angrybirdpark commented on products/tests.py
> +        self.assertEqual(response.status_code, 200)
성공, 쿼리실패(=빈 값), 쿼리성공의 케이스로 나눠서 진행하였습니다..!

2022-04-18 01:27 UTC, lordmyshepherd commented
LGTM 👍🏻

2022-04-18 01:27 UTC, merged