[박광수]"Add: Kakao Login View 작성, login test 작성"
wecode-bootcamp-korea/31-2nd-OldVintage-backend pull request #7
Opened 2022-04-15 11:19 UTC by KwangsooPark607

## :: 최근 작업 주제 (하나 이상의 주제를 선택해주세요.)
- [x] 기능 추가
- [ ] 리뷰 반영
- [ ] 리팩토링
- [ ] 버그 수정
- [ ] 컨벤션 수정

<br />

## :: 구현 목표 (해당 브랜치에서 구현하고자 하는 하나의 목표를 설정합니다.)
- 카카오 로그인 View, Unittest 작성
<br />

## :: 구현 사항 설명 (작업한 내용을 상세하게 기록합니다.)
1. 카카오 로그인 View 작성
2. 카카오 로그인 Unittest 작성
<br />

## :: 성장 포인트 (해당 기능을 구현하며 고민했던 사항이나 새로 알게된 부분, 어려웠던 점 등을 작성합니다.)
- 카카오 로그인 절차에 대해서 공부하면서 requests 를 통해 http request, response 하는 방법을 공부했습니다.
- unittest 작성하는 방법에 대해 공부했습니다.
<br />

## :: 기타 질문 및 특이 사항

2022-04-17 06:21 UTC, lordmyshepherd requested changes

2022-04-17 06:21 UTC, lordmyshepherd commented on users/views.py
> +        self.redirect_url = "http://10.58.7.130:8000/users/kakao/callback"
`redirect_url`은 어디서 사용되나요?

```suggestion
        self.redirect_url = "http://10.58.7.130:8000/users/kakao/callback"
```

2022-04-17 06:21 UTC, lordmyshepherd commented on users/views.py
> +        print(response.json())
프린트문은 지워주세요~

2022-04-17 06:21 UTC, lordmyshepherd commented on users/views.py
> +        response     = requests.post(self.token_url, data)
`requests` 모듈을 사용하실 때에는 `timeout` 옵션을 반드시 설정해주셔야 합니다.
그 이유는 timeout option을 추가하지 않으면 서버의 응답을 계속해서 기다리고 있는 문제가 발생 합니다. timeout 옵션을 추가해 주세요.
```suggestion
        response     = requests.post(self.token_url, data, timeout = ..)
```

2022-04-17 06:21 UTC, lordmyshepherd commented on users/views.py
> +        user_info = requests.get(self.user_url, headers = header)
마찬자기로 `requests` 모듈을 사용하실 때에는 `timeout` 옵션을 반드시 설정해주셔야 합니다.
그 이유는 timeout option을 추가하지 않으면 서버의 응답을 계속해서 기다리고 있는 문제가 발생 합니다. timeout 옵션을 추가해 주세요.
```suggestion
        response     = requests.post(self.token_url, data, timeout = ..)
```

2022-04-17 06:21 UTC, lordmyshepherd commented on users/views.py
> +        response     = requests.post(self.token_url, data)
보통 이렇게 third party 서버의 응답의 성공/실패 여부를 판단할때에는 status 코드로 비교해야 명확하고 디버깅하기 쉽습니다.
```python
response = requests.get(kakao_user_api_url, headers=headers)

if not response.status_code == 200:
    return JsonResponse...

            ..
```

2022-04-17 06:21 UTC, lordmyshepherd commented on users/views.py
> +        print (user_info)
프린트문은 지워주세요~

2022-04-17 06:21 UTC, lordmyshepherd commented on users/views.py
> +        user_info    = KakaoAPI(auth_code).get_user_information(access_token)
KakaoAPI 인스턴스를 두번 만드는 이유는 무엇인가요?

2022-04-18 04:29 UTC, KwangsooPark607 commented on users/views.py
> +        user_info    = KakaoAPI(auth_code).get_user_information(access_token)
인스턴스를 먼저 만들고 변수에 저장해 가져다 쓰는 것으로 수정했습니다ㅏ.

2022-04-18 04:29 UTC, KwangsooPark607 commented on users/views.py
> +        user_info = requests.get(self.user_url, headers = header)
네 추가하겠습니다.

2022-04-18 04:30 UTC, KwangsooPark607 commented on users/views.py
> +        response     = requests.post(self.token_url, data)
네 추가하겠습니다. status코드로 성공/실패 여부 판단도 추가하겠습니다.

2022-04-18 04:31 UTC, KwangsooPark607 commented on users/views.py
> +        self.redirect_url = "http://10.58.7.130:8000/users/kakao/callback"
토큰을 요청하는 함수에서 사용됩니다ㅏ. 추후에 다른 곳에서도 사용하게 될 경우 redirect_url 수정의 편의성도 고려했습니다.

2022-04-18 04:31 UTC, KwangsooPark607 commented
피드백 반영하여 올렸습니다.

2022-04-18 06:04 UTC, lordmyshepherd approved these changes
LGTM 👍🏻

2022-04-18 06:04 UTC, merged